sudo: false
language: python
python:
  # - "2.6"  invalid syntax
  - "2.7"
  # - "3.3"  error install cryptography
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - make
  - pip install --quiet coveralls
script:
  - make test
after_success:
  - make lint coverage
cache: pip