sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy3
install:
- make
- pip install --quiet coveralls
script:
- make test
after_success:
- make lint coverage
deploy:
  provider: pypi
  user: ohara.andrew314
  password:
    secure: BCpC/eYh3aHYM7LOchyd2/boaoMiC5qlvqax7tLMSfNBDB0JDYAMFLdj1T7wcH0wu4r7j9GwUWPN5LBRSUqew9/xKinWD/vtNkdqs8UHBPrvlmLruG2A4rrQACzX13+RaGZ1VopD5w53ywhWpagJpOY04NRQ0L8gkQ+aew9lUBV7aRaM9hOSVuU10cbPIN6yVT3SaqQxg0gv/kf67Dl8kYZ/aAOKcqYAFOJFtbQ2lSH7NssWhI8mCr7SLXORqfG1FAW7CMjpI2jYFZ9r7DBOv4LLaoWPQL/Vvkn19xjXjU+xTWzTGZqVm4smiBTF/DFmERPkvaqNMzmfNCwNkl4BAmn1Qw79cjWZDBDjYcH+qsd4wjWZbKpQzZ+xGVWb8z4aqwLTyRBuTuprl9fnJDP8zLWBlb/FGsGS6PgoyqVJdttypm5d7gIQWub5QI34SgkrgbnC5v+kbotuuF8eZbKnmkLYtzk19EO2C+PomR0CbD2Iuuxp6J42uhyeGUQ3DY5DegMoW1ElPsAw1X05xBpYKXBI3uxhslM4EcQYU/D3XcHpGCBW5kXwH7RJaw1zJvcnpKk1UzukvxIBmQ18xp36zsAgzVL9R54B4ynJfGiW6Y2He1ylXLnUcPC26HK5es/+wb22ua5ZEagqgl7FR7J9Ej8UOGi9Xl8U34x9Gga+Bl0=
cache: pip
